#pragma once
#include <linux/types.h>

enum ssf_cmd_dir {
  SSF_CMD_READ,
  SSF_CMD_WRITE,
};
enum ssf_frame_type {
  SSF_FRAME_FIXED,
  SSF_FRAME_VARIABLE,
};
struct ssf_cmd_desc {
  u8 function;
  enum ssf_cmd_dir direction;
  enum ssf_frame_type frame_type;

  u16 display_reg;
  u16 protocol_addr;
  u16 reg_count;

  const char *name;
};

/*
 * SSF-MEMS-XYZS Modbus command table
 */
static const struct ssf_cmd_desc ssf_cmd_table[] = {
    /* 40001 ~ 40029: sensor measurement data */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40001,
        .protocol_addr = 0x0000,
        .reg_count = 1,
        .name = "x_high_freq_acc_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40002,
        .protocol_addr = 0x0001,
        .reg_count = 1,
        .name = "x_low_freq_velocity_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40003,
        .protocol_addr = 0x0002,
        .reg_count = 1,
        .name = "y_high_freq_acc_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40004,
        .protocol_addr = 0x0003,
        .reg_count = 1,
        .name = "y_low_freq_velocity_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40005,
        .protocol_addr = 0x0004,
        .reg_count = 1,
        .name = "z_high_freq_velocity_acc_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40006,
        .protocol_addr = 0x0005,
        .reg_count = 1,
        .name = "z_low_freq_velocity_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40007,
        .protocol_addr = 0x0006,
        .reg_count = 1,
        .name = "temperature",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40008,
        .protocol_addr = 0x0007,
        .reg_count = 1,
        .name = "x_acc_peak_to_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40009,
        .protocol_addr = 0x0008,
        .reg_count = 1,
        .name = "y_acc_peak_to_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40010,
        .protocol_addr = 0x0009,
        .reg_count = 1,
        .name = "z_acc_peak_to_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40011,
        .protocol_addr = 0x000a,
        .reg_count = 1,
        .name = "x_acc_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40012,
        .protocol_addr = 0x000b,
        .reg_count = 1,
        .name = "y_acc_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40013,
        .protocol_addr = 0x000c,
        .reg_count = 1,
        .name = "z_acc_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40014,
        .protocol_addr = 0x000d,
        .reg_count = 1,
        .name = "x_acc_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40015,
        .protocol_addr = 0x000e,
        .reg_count = 1,
        .name = "y_acc_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40016,
        .protocol_addr = 0x000f,
        .reg_count = 1,
        .name = "z_acc_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40017,
        .protocol_addr = 0x0010,
        .reg_count = 1,
        .name = "x_kurtosis",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40018,
        .protocol_addr = 0x0011,
        .reg_count = 1,
        .name = "y_kurtosis",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40019,
        .protocol_addr = 0x0012,
        .reg_count = 1,
        .name = "z_kurtosis",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40020,
        .protocol_addr = 0x0013,
        .reg_count = 1,
        .name = "x_velocity_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40021,
        .protocol_addr = 0x0014,
        .reg_count = 1,
        .name = "y_velocity_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40022,
        .protocol_addr = 0x0015,
        .reg_count = 1,
        .name = "z_velocity_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40023,
        .protocol_addr = 0x0016,
        .reg_count = 1,
        .name = "sound_rms",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40024,
        .protocol_addr = 0x0017,
        .reg_count = 1,
        .name = "sound_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40025,
        .protocol_addr = 0x0018,
        .reg_count = 1,
        .name = "sound_peak_to_peak",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40026,
        .protocol_addr = 0x0019,
        .reg_count = 1,
        .name = "zero_crossing_rate",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40027,
        .protocol_addr = 0x001a,
        .reg_count = 1,
        .name = "spectral_centroid",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40028,
        .protocol_addr = 0x001b,
        .reg_count = 1,
        .name = "spectral_flux",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40029,
        .protocol_addr = 0x001c,
        .reg_count = 1,
        .name = "startup_flag",
    },

    /* Read all features: 40001 ~ 40029 */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40001,
        .protocol_addr = 0x0000,
        .reg_count = 29,
        .name = "all_features",
    },

    /* 40050 ~ 40053 */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40050,
        .protocol_addr = 0x0031,
        .reg_count = 1,
        .name = "auto_report_enable_read",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40050,
        .protocol_addr = 0x0031,
        .reg_count = 1,
        .name = "auto_report_enable_write",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40051,
        .protocol_addr = 0x0032,
        .reg_count = 1,
        .name = "auto_report_time_read",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40051,
        .protocol_addr = 0x0032,
        .reg_count = 1,
        .name = "auto_report_time_write",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40052,
        .protocol_addr = 0x0033,
        .reg_count = 1,
        .name = "sampling_rate_read",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40052,
        .protocol_addr = 0x0033,
        .reg_count = 1,
        .name = "sampling_rate_write",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40053,
        .protocol_addr = 0x0034,
        .reg_count = 1,
        .name = "sampling_length_read",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40053,
        .protocol_addr = 0x0034,
        .reg_count = 1,
        .name = "sampling_length_write",
    },

    /* 40054 ~ 40056: raw axis data */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_VARIABLE,
        .display_reg = 40054,
        .protocol_addr = 0x0035,
        .reg_count = 1,
        .name = "x_raw_data",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_VARIABLE,
        .display_reg = 40055,
        .protocol_addr = 0x0036,
        .reg_count = 1,
        .name = "y_raw_data",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_VARIABLE,
        .display_reg = 40056,
        .protocol_addr = 0x0037,
        .reg_count = 1,
        .name = "z_raw_data",
    },

    /* 40058 ~ 40060 */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_VARIABLE,
        .display_reg = 40058,
        .protocol_addr = 0x0039,
        .reg_count = 1,
        .name = "start_xyz_continuous",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40059,
        .protocol_addr = 0x003a,
        .reg_count = 1,
        .name = "stop_xyz_continuous",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_VARIABLE,
        .display_reg = 40060,
        .protocol_addr = 0x003b,
        .reg_count = 1,
        .name = "start_custom_length",
    },

    /* 40061 ~ 40071: work parameters */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40061,
        .protocol_addr = 0x003c,
        .reg_count = 1,
        .name = "custom_length_high_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40062,
        .protocol_addr = 0x003d,
        .reg_count = 1,
        .name = "custom_length_low_read",
    },

    /*
     * Manual provides a 0x10 command for writing 40061 ~ 40070.
     */
    {
        .function = 0x10,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40061,
        .protocol_addr = 0x003c,
        .reg_count = 10,
        .name = "write_work_parameters",
    },

    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40063,
        .protocol_addr = 0x003e,
        .reg_count = 1,
        .name = "raw_sound_4096_enable_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40064,
        .protocol_addr = 0x003f,
        .reg_count = 1,
        .name = "x_acc_threshold_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40065,
        .protocol_addr = 0x0040,
        .reg_count = 1,
        .name = "y_acc_threshold_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40066,
        .protocol_addr = 0x0041,
        .reg_count = 1,
        .name = "z_acc_threshold_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40067,
        .protocol_addr = 0x0042,
        .reg_count = 1,
        .name = "x_velocity_threshold_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40068,
        .protocol_addr = 0x0043,
        .reg_count = 1,
        .name = "y_velocity_threshold_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40069,
        .protocol_addr = 0x0044,
        .reg_count = 1,
        .name = "z_velocity_threshold_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40070,
        .protocol_addr = 0x0045,
        .reg_count = 1,
        .name = "parameter_switch_read",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40071,
        .protocol_addr = 0x0046,
        .reg_count = 1,
        .name = "continuous_raw_sound_read",
    },

    /* 40101 ~ 40103 */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40101,
        .protocol_addr = 0x0064,
        .reg_count = 1,
        .name = "slave_addr_read",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40101,
        .protocol_addr = 0x0064,
        .reg_count = 1,
        .name = "slave_addr_write",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40102,
        .protocol_addr = 0x0065,
        .reg_count = 1,
        .name = "baudrate_read",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40102,
        .protocol_addr = 0x0065,
        .reg_count = 1,
        .name = "baudrate_write",
    },
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40103,
        .protocol_addr = 0x0066,
        .reg_count = 1,
        .name = "parity_read",
    },
    {
        .function = 0x06,
        .direction = SSF_CMD_WRITE,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40103,
        .protocol_addr = 0x0066,
        .reg_count = 1,
        .name = "parity_write",
    },

    /* 40121 */
    {
        .function = 0x03,
        .direction = SSF_CMD_READ,
        .frame_type = SSF_FRAME_FIXED,
        .display_reg = 40121,
        .protocol_addr = 0x0078,
        .reg_count = 1,
        .name = "firmware_version",
    },
};

#define SSF_CMD_TABLE_SIZE ARRAY_SIZE(ssf_cmd_table)